import { db } from './db.js';
import { slugify } from './slugify.js';

/**
 * Resolving the two slugs in an invitation URL, allowing for the ones printed
 * on cards that were handed out before somebody edited a slug.
 *
 * Every lookup tries the live slug first and only falls back to `link_aliases`
 * (see the migration), so an alias can never shadow a real invitation — and a
 * slug that is later reused by a different guest keeps its new meaning.
 */

/** The wedding a first URL segment points at, live slug or printed alias. */
export async function resolveWedding(slug) {
  const direct = await db('weddings').where({ slug }).first();
  if (direct) return direct;

  const alias = await db('link_aliases').where({ kind: 'wedding', alias: slug }).first();
  if (!alias) return null;
  return (await db('weddings').where({ id: alias.wedding_id }).first()) || null;
}

/** The guest a second URL segment points at, within an already-resolved wedding. */
export async function resolveGuest(weddingId, slug) {
  const direct = await db('guests').where({ wedding_id: weddingId, slug }).first();
  if (direct) return direct;

  const alias = await db('link_aliases')
    .where({ kind: 'guest', wedding_id: weddingId, alias: slug })
    .first();
  if (!alias || !alias.guest_id) return null;
  return (await db('guests').where({ id: alias.guest_id }).first()) || null;
}

/**
 * Remembers the slug a record is moving away from, so cards already printed
 * with it keep working.
 *
 * Silent on conflict rather than failing the rename: if the old segment is
 * already claimed — most often because this is the second rename and an
 * earlier alias holds it, or an operator mapped it by hand — the existing row
 * is the more deliberate one and is left alone. Losing the alias is a broken
 * QR code; losing the rename would be a failed save.
 */
export async function recordAlias({ kind, alias, weddingId, guestId = null, source = 'rename' }) {
  const clean = slugify(alias);
  if (!clean) return null;

  // Pointless as an alias if a live record already answers to it.
  const taken = kind === 'wedding'
    ? await db('weddings').where({ slug: clean }).first()
    : await db('guests').where({ wedding_id: weddingId, slug: clean }).first();
  if (taken) return null;

  const [row] = await db('link_aliases')
    .insert({ kind, alias: clean, wedding_id: weddingId, guest_id: guestId, source })
    .onConflict()
    .ignore()
    .returning('*');
  return row || null;
}

/**
 * Pulls the slug pair out of whatever the operator pasted — a full invitation
 * URL, or just the path. Anything with one segment is read as an open link
 * and anything with two as a personalised one; deeper paths are rejected
 * rather than guessed at.
 */
export function parseInviteUrl(input) {
  const raw = String(input || '').trim();
  if (!raw) return null;

  // Three shapes reach this in practice: a full link, a bare host with a path
  // (copied out of a browser that hides the scheme), and a bare path. Only the
  // last is safe to treat as a path, so a leading domain is given back its
  // scheme rather than being read as a first slug.
  const hasScheme = raw.includes('://');
  const bareHost = !hasScheme && /^[a-z0-9-]+(\.[a-z0-9-]+)+(\/|$)/i.test(raw);

  let path = raw;
  try {
    const url = hasScheme ? raw
      : bareHost ? `https://${raw}`
      : `https://x/${raw.replace(/^\/+/, '')}`;
    path = new URL(url).pathname;
  } catch {
    return null;
  }

  const parts = path.split('/').map((s) => slugify(decodeURIComponent(s))).filter(Boolean);
  if (parts.length === 1) return { weddingSlug: parts[0], inviteeSlug: null };
  if (parts.length === 2) return { weddingSlug: parts[0], inviteeSlug: parts[1] };
  return null;
}

/**
 * Validates an explicit QR target.
 *
 * Only http(s) is accepted: a QR code is scanned by a phone camera that will
 * hand whatever it finds straight to the OS, so `javascript:`, `data:` and
 * app-scheme URLs have no business being generated by this portal on a
 * guest's behalf. An empty value clears the override.
 */
export function normalizeQrUrl(value) {
  const raw = String(value ?? '').trim();
  if (!raw) return null;

  let url;
  try {
    url = new URL(raw.includes('://') ? raw : `https://${raw}`);
  } catch {
    throw Object.assign(new Error('that is not a valid URL'), { status: 400 });
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw Object.assign(new Error('the QR URL must start with http:// or https://'), { status: 400 });
  }
  if (url.href.length > 2048) {
    throw Object.assign(new Error('that URL is too long for a QR code'), { status: 400 });
  }
  return url.href;
}
